### PR TITLE
Devops

### PR DESCRIPTION
**Pull request by guacke**
@PaulWAyers, I agree with your philosophy [1] and I like the 'tour' you propose! In this PR, I refactor the 'book' (the PR is large because this involved copying files to a new folder), so that
- Github Actions automatically builds your book for every PR to master. I have commented out the option to deploy that build automatically to the course website, but you could enable this to work on push to master.
- You can work in a Docker container (including devcontainer support for VSCode).

Feel free to cherry pick this PR, as I cannot guarantee that I didn't misplace some files during this refactor.

[1] https://www.macvideo.ca/media/Welcome+to+CHEM+3PA3/1_5uetc04h

### CODE REVIEW

**Comment by PaulWAyers** [comment]
Thanks @guacke . It's great to hear from you again.

I knew there was a major refactor needed but @RichRick1 and I had been deferring it until after the course:  hard to build the ship while you're sailing the high seas (we're just trying not to sink the ship and with all souls/students aboard). 

@RichRick1 can we talk on Friday about this, and review what Guillaume has submitted? @msricher , if you'd like to join us, you'd be welcome to do so too.

**Comment by RichRick1** [comment]
Thank you @guacke for a contribution! @PaulWAyers of course, we can review the PR this Friday

**Comment by guacke** [comment]
Great! Do contact me if any of the proposed changes require more context (either in this conversation or via an MS Teams meet).

**Comment by PaulWAyers** [comment]
Thanks @guacke it seems to work well.

**Pull request merged**
